name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      
    - name: Build packages
      run: |
        cd packages/shared-types && npx tsup
        cd ../ui && npx tsup
        
    - name: Lint
      run: |
        cd apps/api && npm run lint
        
    - name: Type check
      run: |
        cd apps/api && npx tsc --noEmit
        cd ../web && npx tsc --noEmit
        
    - name: Test API
      run: |
        cd apps/api
        npx prisma generate
        npm run test
        
    - name: Build applications
      run: |
        cd apps/api && npm run build
        cd ../web && npm run build

  mobile-check:
    name: Mobile App Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      
    - name: Build shared packages
      run: |
        cd packages/shared-types && npx tsup
        cd ../ui && npx tsup
        
    - name: Check Native App
      run: |
        cd apps/native
        npx expo doctor
        npm run build --platform web 